Full_screen = false
Screen_size = { 1920, 1080 }
StartPos = { 0, 0 }
Player_size = 5
Player_color = { 1, 1, 1 }
Movement_increment = 50
Bullet_color = { 1, 0, 0 }
Bullet_speed = 1000
Bullet_size = .05
Bullet_damage = 1
Bullet_lifetime = 500
Bullet_spread = 10
Bullet_delay = 0.1
Bullet_amount = 0
Oscilation_size = 0
Wave_size = 0
Reflection_innaccuracy = 0
Bullet_random_speed_factor = 0
Bullet_death_speed_factor = 0
Bullet_speed_slow_factor = 0
Scroll_multiplier = .1
